# Generated by Django 4.0.6 on 2022-09-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0052_rename_rate_comment_rate_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('me', models.CharField(max_length=200)),
            ],
        ),
    ]
