# Generated by Django 4.0.6 on 2022-09-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0053_translatepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TranslatePage',
        ),
    ]
